services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_DB=dealer-webapp'
    ports:
      - "5432:5432"
    expose:
      - "5432"