spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dealer-webapp
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

server:
  port: 8080

dealer-webapp:
  security:
    jwt:
      secret: ee60ad300ec74f5eb736bd1e08845012d748a7737a2d5541b9be3842329d2745
      expiration: 86400000
      expiration-refresh: 604800000
